// app/layout.js
import './globals.scss';
import CustomCursor from '../components/customcursor';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <CustomCursor />
      {children}
      </body>
    </html>
  );
}
